import { db } from '@/db';
import { spareParts } from '@/db/schema';

async function main() {
    const sampleSpareParts = [
        {
            partNumber: 'SP-FIL-001',
            name: 'Engine Oil Filter',
            category: 'Filter',
            description: 'High-quality engine oil filter compatible with Maruti, Hyundai, and Tata vehicles',
            unitPrice: 350,
            stockQuantity: 45,
            reorderPoint: 10,
            vendorId: 1,
            location: 'Shelf-A1',
            status: 'active',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            partNumber: 'SP-BRK-001',
            name: 'Brake Pad Set (Front)',
            category: 'Brake',
            description: 'Premium ceramic brake pads for superior stopping power',
            unitPrice: 1850,
            stockQuantity: 28,
            reorderPoint: 8,
            vendorId: 2,
            location: 'Shelf-B2',
            status: 'active',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            partNumber: 'SP-ELC-001',
            name: 'Headlight Assembly',
            category: 'Electrical',
            description: 'Complete LED headlight assembly with DRL for premium models',
            unitPrice: 4500,
            stockQuantity: 12,
            reorderPoint: 5,
            vendorId: 3,
            location: 'Rack-C3',
            status: 'active',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            partNumber: 'SP-BDY-001',
            name: 'Bumper Front',
            category: 'Body Parts',
            description: 'Unpainted front bumper assembly for Maruti Swift',
            unitPrice: 3200,
            stockQuantity: 8,
            reorderPoint: 5,
            vendorId: 1,
            location: 'Bay-D1',
            status: 'active',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            partNumber: 'SP-FIL-002',
            name: 'Air Filter',
            category: 'Filter',
            description: 'High-flow air filter for improved engine performance',
            unitPrice: 650,
            stockQuantity: 35,
            reorderPoint: 10,
            vendorId: 2,
            location: 'Shelf-A2',
            status: 'active',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            partNumber: 'SP-SUS-001',
            name: 'Shock Absorber',
            category: 'Suspension',
            description: 'Gas-filled shock absorber for smooth ride quality',
            unitPrice: 2800,
            stockQuantity: 16,
            reorderPoint: 6,
            vendorId: 3,
            location: 'Rack-E2',
            status: 'active',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            partNumber: 'SP-ENG-001',
            name: 'Radiator',
            category: 'Engine',
            description: 'Aluminum radiator with efficient cooling capacity',
            unitPrice: 4800,
            stockQuantity: 7,
            reorderPoint: 5,
            vendorId: 1,
            location: 'Bay-F1',
            status: 'inactive',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            partNumber: 'SP-BDY-002',
            name: 'Wiper Blade Set',
            category: 'Body Parts',
            description: 'Premium silicone wiper blades pair for all-weather performance',
            unitPrice: 580,
            stockQuantity: 42,
            reorderPoint: 8,
            vendorId: 2,
            location: 'Shelf-G3',
            status: 'active',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            partNumber: 'SP-ENG-002',
            name: 'Spark Plug Set',
            category: 'Engine',
            description: 'Iridium spark plugs set of 4 for enhanced fuel efficiency',
            unitPrice: 1200,
            stockQuantity: 24,
            reorderPoint: 8,
            vendorId: 3,
            location: 'Shelf-A3',
            status: 'active',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            partNumber: 'SP-ELC-002',
            name: 'Battery 12V',
            category: 'Electrical',
            description: '12V 65Ah maintenance-free automotive battery with 3-year warranty',
            unitPrice: 5500,
            stockQuantity: 6,
            reorderPoint: 5,
            vendorId: 1,
            location: 'Bay-H1',
            status: 'inactive',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ];

    await db.insert(spareParts).values(sampleSpareParts);
    
    console.log('✅ Spare parts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});