import { db } from '@/db';
import { vehicles } from '@/db/schema';

async function main() {
    const now = Date.now();
    const oneDay = 24 * 60 * 60 * 1000;
    
    const sampleVehicles = [
        {
            vin: '1HGBH41JXMN109186',
            make: 'Toyota',
            model: 'RAV4',
            year: 2023,
            category: 'SUV',
            color: 'White',
            price: 32500,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (30 * oneDay),
            updatedAt: now - (5 * oneDay),
        },
        {
            vin: '2T1BURHE5JC123456',
            make: 'Honda',
            model: 'CR-V',
            year: 2024,
            category: 'SUV',
            color: 'Black',
            price: 35200,
            stock: 12,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (25 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: '1FM5K8D85LGA12345',
            make: 'Ford',
            model: 'Explorer',
            year: 2022,
            category: 'SUV',
            color: 'Silver',
            price: 38900,
            stock: 6,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (45 * oneDay),
            updatedAt: now - (10 * oneDay),
        },
        {
            vin: '1GNSKCKC9KR234567',
            make: 'Chevrolet',
            model: 'Tahoe',
            year: 2023,
            category: 'SUV',
            color: 'Blue',
            price: 58750,
            stock: 3,
            reorderPoint: 3,
            status: 'reserved',
            createdAt: now - (20 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: '1HGCV1F30KA345678',
            make: 'Honda',
            model: 'Accord',
            year: 2024,
            category: 'Sedan',
            color: 'Gray',
            price: 28450,
            stock: 9,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (15 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: '4T1C11AK2MU456789',
            make: 'Toyota',
            model: 'Camry',
            year: 2023,
            category: 'Sedan',
            color: 'Red',
            price: 26800,
            stock: 11,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (35 * oneDay),
            updatedAt: now - (7 * oneDay),
        },
        {
            vin: 'WBA8E1C55KA567890',
            make: 'BMW',
            model: '3 Series',
            year: 2024,
            category: 'Sedan',
            color: 'White',
            price: 45200,
            stock: 4,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (12 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: 'WDDWF4KB5KA678901',
            make: 'Mercedes-Benz',
            model: 'C-Class',
            year: 2023,
            category: 'Sedan',
            color: 'Black',
            price: 48900,
            stock: 2,
            reorderPoint: 4,
            status: 'sold',
            createdAt: now - (40 * oneDay),
            updatedAt: now - (14 * oneDay),
        },
        {
            vin: '1FTEW1EP5LKC789012',
            make: 'Ford',
            model: 'F-150',
            year: 2022,
            category: 'Truck',
            color: 'Blue',
            price: 42300,
            stock: 7,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (50 * oneDay),
            updatedAt: now - (8 * oneDay),
        },
        {
            vin: '1GCRYDED5KZ890123',
            make: 'Chevrolet',
            model: 'Silverado',
            year: 2023,
            category: 'Truck',
            color: 'Silver',
            price: 44800,
            stock: 5,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (28 * oneDay),
            updatedAt: now - (4 * oneDay),
        },
        {
            vin: '3TMCZ5AN7KM901234',
            make: 'Toyota',
            model: 'Tacoma',
            year: 2024,
            category: 'Truck',
            color: 'Gray',
            price: 38500,
            stock: 6,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (18 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: '5YJ3E1EA5KF012345',
            make: 'Tesla',
            model: 'Model 3',
            year: 2023,
            category: 'EV',
            color: 'White',
            price: 47240,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (22 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: '5YJYGDEE5KF123456',
            make: 'Tesla',
            model: 'Model Y',
            year: 2024,
            category: 'EV',
            color: 'Red',
            price: 52690,
            stock: 10,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (10 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: '1N4AZ1CP5KC234567',
            make: 'Nissan',
            model: 'Leaf',
            year: 2022,
            category: 'EV',
            color: 'Blue',
            price: 31620,
            stock: 4,
            reorderPoint: 4,
            status: 'reserved',
            createdAt: now - (33 * oneDay),
            updatedAt: now - (6 * oneDay),
        },
        {
            vin: '1G1FY6S00K4345678',
            make: 'Chevrolet',
            model: 'Bolt',
            year: 2023,
            category: 'EV',
            color: 'Green',
            price: 28800,
            stock: 3,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (38 * oneDay),
            updatedAt: now - (9 * oneDay),
        },
        {
            vin: 'KMHL14JA5KA456789',
            make: 'Hyundai',
            model: 'Elantra',
            year: 2024,
            category: 'Sedan',
            color: 'Silver',
            price: 23400,
            stock: 13,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (16 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'WAUZZZ8V2KA567890',
            make: 'Audi',
            model: 'A4',
            year: 2023,
            category: 'Sedan',
            color: 'Black',
            price: 52400,
            stock: 5,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (27 * oneDay),
            updatedAt: now - (5 * oneDay),
        },
        {
            vin: '1HGCV2F85JA678901',
            make: 'Honda',
            model: 'Civic',
            year: 2021,
            category: 'Sedan',
            color: 'White',
            price: 24800,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (60 * oneDay),
            updatedAt: now - (15 * oneDay),
        },
        {
            vin: '5NPE34AF5KH789012',
            make: 'Hyundai',
            model: 'Tucson',
            year: 2023,
            category: 'SUV',
            color: 'Gray',
            price: 33200,
            stock: 9,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (24 * oneDay),
            updatedAt: now - (4 * oneDay),
        },
        {
            vin: '1G1BE5SM7J7890123',
            make: 'Chevrolet',
            model: 'Malibu',
            year: 2020,
            category: 'Sedan',
            color: 'Blue',
            price: 22500,
            stock: 2,
            reorderPoint: 3,
            status: 'sold',
            createdAt: now - (75 * oneDay),
            updatedAt: now - (20 * oneDay),
        },
        {
            vin: 'JM1CX1GL5K0901234',
            make: 'Mazda',
            model: 'CX-5',
            year: 2024,
            category: 'SUV',
            color: 'Red',
            price: 36400,
            stock: 6,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (14 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: '1N4AL3AP5KC012345',
            make: 'Nissan',
            model: 'Altima',
            year: 2022,
            category: 'Sedan',
            color: 'Silver',
            price: 26300,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (42 * oneDay),
            updatedAt: now - (7 * oneDay),
        },
        {
            vin: 'WBAXA1C50KC123456',
            make: 'BMW',
            model: 'X1',
            year: 2023,
            category: 'SUV',
            color: 'Black',
            price: 49800,
            stock: 4,
            reorderPoint: 3,
            status: 'reserved',
            createdAt: now - (19 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: '2HKRM4H73KH234567',
            make: 'Honda',
            model: 'Pilot',
            year: 2024,
            category: 'SUV',
            color: 'White',
            price: 42700,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (11 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: '1FTFW1ET5KFC345678',
            make: 'Ford',
            model: 'F-250',
            year: 2023,
            category: 'Truck',
            color: 'Gray',
            price: 54900,
            stock: 3,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (32 * oneDay),
            updatedAt: now - (6 * oneDay),
        },
        {
            vin: '4T1K61AK5LU456789',
            make: 'Toyota',
            model: 'Corolla',
            year: 2021,
            category: 'Sedan',
            color: 'Blue',
            price: 21800,
            stock: 12,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (55 * oneDay),
            updatedAt: now - (12 * oneDay),
        },
        {
            vin: '5YJ3E1EB5KF567890',
            make: 'Tesla',
            model: 'Model 3',
            year: 2024,
            category: 'EV',
            color: 'Black',
            price: 49240,
            stock: 6,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (8 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: 'KMHD84LF5KU678901',
            make: 'Hyundai',
            model: 'Sonata',
            year: 2022,
            category: 'Sedan',
            color: 'Silver',
            price: 28900,
            stock: 5,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (29 * oneDay),
            updatedAt: now - (5 * oneDay),
        },
        {
            vin: 'JN8AZ2KR9K9789012',
            make: 'Nissan',
            model: 'Murano',
            year: 2023,
            category: 'SUV',
            color: 'Red',
            price: 41300,
            stock: 4,
            reorderPoint: 3,
            status: 'reserved',
            createdAt: now - (21 * oneDay),
            updatedAt: now - (4 * oneDay),
        },
        {
            vin: 'WDDGF4HB5KA890123',
            make: 'Mercedes-Benz',
            model: 'E-Class',
            year: 2024,
            category: 'Sedan',
            color: 'White',
            price: 62900,
            stock: 3,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (13 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: '1C4RJFAG5KC901234',
            make: 'Jeep',
            model: 'Grand Cherokee',
            year: 2023,
            category: 'SUV',
            color: 'Green',
            price: 46800,
            stock: 6,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (26 * oneDay),
            updatedAt: now - (4 * oneDay),
        },
        {
            vin: '3C6RR7LT5KG012345',
            make: 'Ram',
            model: '1500',
            year: 2022,
            category: 'Truck',
            color: 'Black',
            price: 48200,
            stock: 4,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (37 * oneDay),
            updatedAt: now - (8 * oneDay),
        },
        {
            vin: 'WAUZZZF12KA123456',
            make: 'Audi',
            model: 'Q5',
            year: 2024,
            category: 'SUV',
            color: 'Gray',
            price: 57200,
            stock: 5,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (17 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: '1G1FW6S07K4234567',
            make: 'Chevrolet',
            model: 'Bolt EUV',
            year: 2023,
            category: 'EV',
            color: 'Blue',
            price: 32500,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (23 * oneDay),
            updatedAt: now - (4 * oneDay),
        },
        {
            vin: 'JTDKARFP5K3345678',
            make: 'Toyota',
            model: 'Prius',
            year: 2021,
            category: 'Sedan',
            color: 'White',
            price: 24800,
            stock: 2,
            reorderPoint: 4,
            status: 'sold',
            createdAt: now - (48 * oneDay),
            updatedAt: now - (16 * oneDay),
        },
        {
            vin: '1FMCU9GD5KUA456789',
            make: 'Ford',
            model: 'Escape',
            year: 2024,
            category: 'SUV',
            color: 'Silver',
            price: 34600,
            stock: 9,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (9 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: '5NPF34AF8KH567890',
            make: 'Hyundai',
            model: 'Santa Fe',
            year: 2023,
            category: 'SUV',
            color: 'Black',
            price: 39400,
            stock: 6,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (31 * oneDay),
            updatedAt: now - (6 * oneDay),
        },
        {
            vin: '1N4BZ1CP5KC678901',
            make: 'Nissan',
            model: 'Sentra',
            year: 2022,
            category: 'Sedan',
            color: 'Gray',
            price: 22400,
            stock: 10,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (41 * oneDay),
            updatedAt: now - (8 * oneDay),
        },
        {
            vin: '1HGCV1F13KA789012',
            make: 'Honda',
            model: 'Accord Hybrid',
            year: 2024,
            category: 'Sedan',
            color: 'Blue',
            price: 33200,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (7 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: '5YJSA1E22KF890123',
            make: 'Tesla',
            model: 'Model S',
            year: 2023,
            category: 'EV',
            color: 'Red',
            price: 78490,
            stock: 2,
            reorderPoint: 3,
            status: 'reserved',
            createdAt: now - (36 * oneDay),
            updatedAt: now - (7 * oneDay),
        }
    ];

    await db.insert(vehicles).values(sampleVehicles);
    
    console.log('✅ Vehicles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});