import { db } from '@/db';
import { vehicles } from '@/db/schema';

async function main() {
    const now = Date.now();
    const thirtyDaysAgo = now - (30 * 24 * 60 * 60 * 1000);
    const fiveDaysAgo = now - (5 * 24 * 60 * 60 * 1000);

    const sampleVehicles = [
        {
            vin: 'MA3ERLF1S00C45678',
            make: 'Maruti Suzuki',
            model: 'Swift',
            year: 2024,
            category: 'Hatchback',
            color: 'Nexa Blue',
            price: 850000,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (2 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (1 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'MA3ERLF1S00C45679',
            make: 'Maruti Suzuki',
            model: 'Baleno',
            year: 2024,
            category: 'Hatchback',
            color: 'Pearl White',
            price: 920000,
            stock: 12,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (5 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (2 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'MA3ERLF1S00C45680',
            make: 'Maruti Suzuki',
            model: 'Brezza',
            year: 2024,
            category: 'SUV',
            color: 'Splendid Silver',
            price: 1250000,
            stock: 6,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (8 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (3 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'MA3ERLF1S00C45681',
            make: 'Maruti Suzuki',
            model: 'Ertiga',
            year: 2023,
            category: 'MPV',
            color: 'Dazzling Silver',
            price: 1450000,
            stock: 5,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (10 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (1 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'MA3ERLF1S00C45682',
            make: 'Maruti Suzuki',
            model: 'Dzire',
            year: 2024,
            category: 'Sedan',
            color: 'Intense Red',
            price: 950000,
            stock: 10,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (12 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (4 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'MA3ERLF1S00C45683',
            make: 'Maruti Suzuki',
            model: 'Grand Vitara',
            year: 2024,
            category: 'SUV',
            color: 'Everest White',
            price: 1850000,
            stock: 4,
            reorderPoint: 3,
            status: 'reserved',
            createdAt: thirtyDaysAgo + (15 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo,
        },
        {
            vin: 'TAT3NEXON00D12345',
            make: 'Tata',
            model: 'Nexon',
            year: 2024,
            category: 'SUV',
            color: 'Foliage Green',
            price: 1300000,
            stock: 9,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (3 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (2 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'TAT3NEXON00D12346',
            make: 'Tata',
            model: 'Nexon EV',
            year: 2024,
            category: 'EV',
            color: 'Daytona Grey',
            price: 1650000,
            stock: 7,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (6 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (1 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'TAT3ALTROZ0D12347',
            make: 'Tata',
            model: 'Altroz',
            year: 2024,
            category: 'Hatchback',
            color: 'Downtown Red',
            price: 880000,
            stock: 11,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (9 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (3 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'TAT3HARRIER0D12348',
            make: 'Tata',
            model: 'Harrier',
            year: 2024,
            category: 'SUV',
            color: 'Oberon Black',
            price: 2050000,
            stock: 5,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (11 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (2 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'TAT3SAFARI00D12349',
            make: 'Tata',
            model: 'Safari',
            year: 2023,
            category: 'SUV',
            color: 'Tropical Mist',
            price: 2350000,
            stock: 4,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (14 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (1 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'TAT3PUNCH000D12350',
            make: 'Tata',
            model: 'Punch',
            year: 2024,
            category: 'SUV',
            color: 'Calypso Red',
            price: 1150000,
            stock: 13,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (17 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (4 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'TAT3TIGOREV0D12351',
            make: 'Tata',
            model: 'Tigor EV',
            year: 2024,
            category: 'EV',
            color: 'Glacier White Pearl',
            price: 1550000,
            stock: 6,
            reorderPoint: 3,
            status: 'reserved',
            createdAt: thirtyDaysAgo + (19 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo,
        },
        {
            vin: 'MAH3XUV700E00V123',
            make: 'Mahindra',
            model: 'XUV700',
            year: 2024,
            category: 'SUV',
            color: 'Midnight Black',
            price: 2250000,
            stock: 5,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (4 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (2 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'MAH3THAR000E00V124',
            make: 'Mahindra',
            model: 'Thar',
            year: 2024,
            category: 'SUV',
            color: 'Ranger Khaki',
            price: 1950000,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (7 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (3 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'MAH3SCORPIO0V125',
            make: 'Mahindra',
            model: 'Scorpio-N',
            year: 2024,
            category: 'SUV',
            color: 'Rocky Beige',
            price: 1850000,
            stock: 6,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (13 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (1 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'MAH3XUV300E00V126',
            make: 'Mahindra',
            model: 'XUV300',
            year: 2023,
            category: 'SUV',
            color: 'Red Rage',
            price: 1350000,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (16 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (2 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'MAH3BOLERO0E0V127',
            make: 'Mahindra',
            model: 'Bolero Neo',
            year: 2024,
            category: 'SUV',
            color: 'Opulent Red',
            price: 1180000,
            stock: 9,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (18 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (4 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'HYU3CRETA00F00X78',
            make: 'Hyundai',
            model: 'Creta',
            year: 2024,
            category: 'SUV',
            color: 'Polar White',
            price: 1750000,
            stock: 10,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (1 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (1 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'HYU3VENUE00F00X79',
            make: 'Hyundai',
            model: 'Venue',
            year: 2024,
            category: 'SUV',
            color: 'Stargazing Blue',
            price: 1280000,
            stock: 12,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (20 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (3 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'HYU3I20000F000X80',
            make: 'Hyundai',
            model: 'i20',
            year: 2024,
            category: 'Hatchback',
            color: 'Fiery Red',
            price: 890000,
            stock: 14,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (22 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (2 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'HYU3VERNA00F00X81',
            make: 'Hyundai',
            model: 'Verna',
            year: 2024,
            category: 'Sedan',
            color: 'Phantom Black',
            price: 1350000,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (24 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (1 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'HYU3ALCAZAR0X82',
            make: 'Hyundai',
            model: 'Alcazar',
            year: 2023,
            category: 'SUV',
            color: 'Titan Grey',
            price: 1950000,
            stock: 5,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (26 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (4 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'HYU3EXTER00F00X83',
            make: 'Hyundai',
            model: 'Exter',
            year: 2024,
            category: 'SUV',
            color: 'Canyon River Blue',
            price: 1120000,
            stock: 11,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (28 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (3 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'KIA3SELTOS0G00Y45',
            make: 'Kia',
            model: 'Seltos',
            year: 2024,
            category: 'SUV',
            color: 'Imperial Blue',
            price: 1680000,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (21 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (2 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'KIA3SONET00G00Y46',
            make: 'Kia',
            model: 'Sonet',
            year: 2024,
            category: 'SUV',
            color: 'Aurora Black Pearl',
            price: 1250000,
            stock: 10,
            reorderPoint: 4,
            status: 'reserved',
            createdAt: thirtyDaysAgo + (23 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo,
        },
        {
            vin: 'KIA3CARENS0G00Y47',
            make: 'Kia',
            model: 'Carens',
            year: 2024,
            category: 'MPV',
            color: 'Platinum White Pearl',
            price: 1620000,
            stock: 6,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (25 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (1 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'HON3CITY000H00Z89',
            make: 'Honda',
            model: 'City',
            year: 2024,
            category: 'Sedan',
            color: 'Radiant Red Metallic',
            price: 1280000,
            stock: 9,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (27 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (2 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'HON3AMAZE00H00Z90',
            make: 'Honda',
            model: 'Amaze',
            year: 2024,
            category: 'Sedan',
            color: 'Silky Silver',
            price: 980000,
            stock: 13,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (29 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (3 * 24 * 60 * 60 * 1000),
        },
        {
            vin: 'HON3ELEVATE0Z91',
            make: 'Honda',
            model: 'Elevate',
            year: 2024,
            category: 'SUV',
            color: 'Phoenix Red',
            price: 1550000,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: thirtyDaysAgo + (4 * 24 * 60 * 60 * 1000),
            updatedAt: fiveDaysAgo + (4 * 24 * 60 * 60 * 1000),
        },
    ];

    await db.insert(vehicles).values(sampleVehicles);
    
    console.log('✅ Vehicles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});